export const mockData = [
  {
    key: "1",
    name: "Tony Reichert",
    pic: "https://yt4.ggpht.com/ytc/AOPolaRyc4u5TCsT76h1lNuQYPbJOzEK9OTdrhguwB6d=s32-c-k-c0x00ffffff-no-rj",
    message: "CEO",
    type: "textMessageEvent",
    time: "2023-09-14T13:06:39.855014+00:00",
    isChatOwner: false,
    isChatSponsor: true,
    isChatModerator: false,
  },
  {
    key: "2",
    name: "Zoey Lang",
    pic: "https://yt4.ggpht.com/ytc/AOPolaRyc4u5TCsT76h1lNuQYPbJOzEK9OTdrhguwB6d=s32-c-k-c0x00ffffff-no-rj",
    message: "Technical Lead",
    type: "textMessageEvent",
    time: "2023-09-14T13:06:39.855014+00:00",
    isChatOwner: false,
    isChatSponsor: true,
    isChatModerator: false,
  },
  {
    key: "3",
    name: "Jane Fisher",
    pic: "https://yt4.ggpht.com/ytc/AOPolaRyc4u5TCsT76h1lNuQYPbJOzEK9OTdrhguwB6d=s32-c-k-c0x00ffffff-no-rj",
    message: "Senior Developer",
    type: "textMessageEvent",
    time: "2023-09-14T13:06:39.855014+00:00",
    isChatOwner: false,
    isChatSponsor: true,
    isChatModerator: false,
  },
  {
    key: "4",
    name: "William Howard",
    pic: "https://yt4.ggpht.com/ytc/AOPolaRyc4u5TCsT76h1lNuQYPbJOzEK9OTdrhguwB6d=s32-c-k-c0x00ffffff-no-rj",
    message: "Community Manager",
    type: "textMessageEvent",
    time: "2023-09-14T13:06:39.855014+00:00",
    isChatOwner: false,
    isChatSponsor: true,
    isChatModerator: false,
  },
  {
    key: "5",
    name: "Long long long long long long name test",
    pic: "https://yt4.ggpht.com/ytc/AOPolaRyc4u5TCsT76h1lNuQYPbJOzEK9OTdrhguwB6d=s32-c-k-c0x00ffffff-no-rj",
    message:
      "I am going to do it. I have made up my mind. These are the first few words of the new… the best … the Longest Text In The Entire History Of The Known Universe! This Has To Have Over 35,000 words the beat the current world record set by that person who made that flaming chicken handbooky thingy. I might just be saying random things the whole time I type in this so you might get confused a lot. I just discovered something terrible. autocorrect is on!! no!!! this has to be crazy, so I will have to break all the English language rules and the basic knowledge of the average human being. I am not an average human being, however I am special. no no no, not THAT kind of special ;). Why do people send that wink face! it always gives me nightmares! it can make a completely normal sentence creepy. imagine you are going to a friend’s house, so you text this: [ see you soon 🙂 ] seems normal, right? But what is you add the word semi to that colon? (Is that right? or is it the other way around) what is you add a lorry to that briquettes? (Semi-truck to that coal-on) anyway, back to the point: [ see you soon 😉 ]THAT IS JUST SO CREEPY! is that really your friend, or is it a creepy stalker watching your every move? Or even worse, is it your friend who is a creepy stalker? maybe you thought it was your friend, but it was actually your fri end (let me explain: you are happily in McDonalds, getting fat while eating yummy food and some random dude walks up and blots out the sun (he looks like a regular here) you can’t see anything else than him, so you can’t try to avoid eye contact. he finishes eating his cheeseburger (more like horseburgher(I learned that word from the merchant of Venice(which is a good play(if you can understand it(I can cause I got a special book with all the words in readable English written on the side of the page(which is kinda funny because Shakespeare was supposed to be a good poet but no-one can understand him(and he’s racist in act 2 scene1 of the play too))))))) and sits down beside you , like you are old pals (you’ve never met him before but he looks like he could be in some weird cult) he clears his throat and asks you a very personal question. “can i have some French fries?” (I don’t know why there called French fries when I’ve never seen a French person eat fries! all they eat it is stuff like baguettes and crêpes and rats named ratty-two-ee which is a really fun game on the PlayStation 2) And you think {bubbly cloud thinking bubble} “Hahahahahhahahahahahahahaha!!!!!!!!!!!!",
    type: "textMessageEvent",
    time: "2023-09-14T13:06:39.855014+00:00",
    isChatOwner: false,
    isChatSponsor: true,
    isChatModerator: false,
  },
  {
    key: "6",
    name: "Long long long long long long name test",
    pic: "https://yt4.ggpht.com/ytc/AOPolaRyc4u5TCsT76h1lNuQYPbJOzEK9OTdrhguwB6d=s32-c-k-c0x00ffffff-no-rj",
    message: "88米88貓",
    type: "textMessageEvent",
    time: "2023-09-14T13:06:39.855014+00:00",
    isChatOwner: false,
    isChatSponsor: true,
    isChatModerator: false,
  },
  {
    key: "7",
    name: "Long long long long long long name test",
    pic: "https://yt4.ggpht.com/ytc/AOPolaRyc4u5TCsT76h1lNuQYPbJOzEK9OTdrhguwB6d=s32-c-k-c0x00ffffff-no-rj",
    message: "88米88貓",
    type: "textMessageEvent",
    time: "2023-09-14T13:06:39.855014+00:00",
    isChatOwner: false,
    isChatSponsor: true,
    isChatModerator: false,
  },
  {
    key: "8",
    name: "Long long long long long long name test",
    pic: "https://yt4.ggpht.com/ytc/AOPolaRyc4u5TCsT76h1lNuQYPbJOzEK9OTdrhguwB6d=s32-c-k-c0x00ffffff-no-rj",
    message: "邀月白銀 gifted 5 米亞 Mya memberships",
    type: "membershipGiftingEvent",
    time: "2023-09-14T13:06:39.855014+00:00",
    isChatOwner: false,
    isChatSponsor: true,
    isChatModerator: false,
  },
  {
    key: "9",
    name: "Long long long long long long name test",
    pic: "https://yt4.ggpht.com/ytc/AOPolaRyc4u5TCsT76h1lNuQYPbJOzEK9OTdrhguwB6d=s32-c-k-c0x00ffffff-no-rj",
    message:
      'HK$500.00 from 熊貓Derek: "聽日有ip15買:_變態panda: 雖然唔知有冇得點歌, 但想點野狼disco:_happypanda:"',
    type: "superChatEvent",
    time: "2023-09-14T13:06:39.855014+00:00",
    isChatOwner: true,
    isChatSponsor: true,
    isChatModerator: true,
  },
  {
    key: "10",
    name: "Long long long long long long name test",
    pic: "https://yt4.ggpht.com/ytc/AOPolaRyc4u5TCsT76h1lNuQYPbJOzEK9OTdrhguwB6d=s32-c-k-c0x00ffffff-no-rj",
    message: "88米88貓",
    type: "textMessageEvent",
    time: "2023-09-14T13:06:39.855014+00:00",
    isChatOwner: true,
    isChatSponsor: true,
    isChatModerator: false,
  },
];
